# oasis/Makefile -- stub makefile
#
# last modified:   27-Aug-2004  Fri  15:54
#
# Copyright (c) 2004 SoftJin Infotech Private Ltd.
# This software may be used only under the terms of the SoftJin
# Source License.  See the accompanying file LICENSE for details.

all:
	cd ..;  $(MAKE) oasis_all

clean:
	cd ..;  $(MAKE) oasis_clean
